### ISSUE TITLE
Tooltip does not display pet species

### ISSUE THREAD

**Issue by wadergirl** [Jaliborc/PetTracker-Broker#1]
This has also been reported on the main PetTracker page, just want to make sure to cover the bases.
https://github.com/Jaliborc/PetTracker/issues/211

**Running Software**:
Addon version: PetTracker_Broker-8.0.1-8.3.0.zip
Server patch: 8.3.7 35662 (Release  x64)

**Have you read the changelog?** 
Yes

**Describe the Bug**
Tooltip only has the pet progress bar. No species list as expected per addon description.

**Steps to Reproduce the Behavior**:
Mouseover the databroker display to show tooltip.  Broker being used with ChocolateBar.

**Expected Behavior**
Tooltip displays tracker bar and species list per screenshot on Twitch/Curseforge
![](https://user-images.githubusercontent.com/5632219/93584049-c54d8000-f972-11ea-92e3-f4a2ebf8b966.png)

**Screenshots**
Tooltip displays tracker bar only
![image](https://user-images.githubusercontent.com/72587392/95534317-1f0dfc80-09ab-11eb-99cb-557aca0b9556.png)

**Error Logs**
No script error

**Additional context**
N/A

**Comment by Jaliborc** [comment]
Fixed
